# Generated by Django 3.2.22 on 2023-10-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='../default_trip_b4mj7o', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('1', 'Fleet'), ('2', 'Racing'), ('3', 'Parasailing'), ('4', 'eSailing'), ('5', 'Offshore'), ('6', 'Cruising'), ('7', 'Radio')], default='Sightseeing', max_length=255)),
                ('trip_categories', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
